###
#   https://nil.udemy.com/course/elasticsearch-complete-guide/learn/lecture/16287978#overview
###

###
GET http://{{$dotenv ELASTIC}}/_cluster/health


###
GET http://{{$dotenv ELASTIC}}/_cat/nodes?v


###
GET http://{{$dotenv ELASTIC}}/_nodes


###
GET http://{{$dotenv ELASTIC}}/_cat/indices

