###
PUT http://{{$dotenv ELASTIC}}/_template/access-logs
Content-Type: application/json

{
    "index_patterns": ["access-logs-*"],
    "settings": {
        "number_of_shards": 2,
        "index.mapping.coerce": false
    },
    "mappings": {
        "properties":{
            "@timestamp":{
                "type": "date"
            },
            "url.original":{
                "type": "keyword"
            },
            "http.request.referrer":{
                "type": "keyword"
            },
            "http.response.status_code":{
                "type": "long"
            }
        }
    }
}

###
PUT http://{{$dotenv ELASTIC}}/access-logs-2020-01-01

###
GET http://{{$dotenv ELASTIC}}/access-logs-2020-01-01

