PUT http://{{$processEnv ELASTIC}}/multi_field_test
Content-Type: application/json

{
    "mappings": {
        "properties": {
            "description":{
                "type":"text"
            },
            "ingredients":{
                "type": "text",
                "fields":{
                    "keyword": {
                        "type": "keyword"
                    }
                }
            }
        }
    }
}

###
POST http://{{$processEnv ELASTIC}}/multi_field_test/_doc
Content-Type: application/json

{
    "description": "To make this spaghetti carbonara, you first need to ...",
    "ingredients": ["Spaghetti", "Guanciale", "Eggs"]
}


###
GET http://{{$processEnv ELASTIC}}/multi_field_test/_search
Content-Type: application/json

{
    "query":{
        "match_all": {}
    }
}

###
GET http://{{$processEnv ELASTIC}}/multi_field_test/_search
Content-Type: application/json

{
    "query":{
        "match": {
            "ingredients": "Spaghetti"
        }
    }
}

###
GET http://{{$processEnv ELASTIC}}/multi_field_test/_search
Content-Type: application/json

{
    "query":{
        "match": {
            "ingredients": "spaghetti"
        }
    }
}


###
GET http://{{$processEnv ELASTIC}}/multi_field_test/_search
Content-Type: application/json

{
    "query":{
        "term": {
            "ingredients.keyword": "spaghetti"
        }
    }
}

###
GET http://{{$processEnv ELASTIC}}/multi_field_test/_search
Content-Type: application/json

{
    "query":{
        "term": {
            "ingredients.keyword": "Spaghetti"
        }
    }
}
