###
POST http://{{$processEnv ELASTIC}}/reviews/_doc
Content-Type: application/json

{
    "rating": 4.5,
    "content": "Not bad. Not bad at all!",
    "product_id": 123,
    "created_at": "2015-03-27",
    "author": { 
        "first_name": "Average",
        "last_name": "Joe",
        "email": "avgjoe@example.com"
    }
}


###
POST http://{{$processEnv ELASTIC}}/reviews/_doc
Content-Type: application/json

{
    "rating": 3.5,
    "content": "Could be better!",
    "product_id": 123,
    "created_at": "2015-04-15T13:07:41Z",
    "author": { 
        "first_name": "Spencer",
        "last_name": "Pearson",
        "email": "spearson@example.com"
    }
}

###
POST http://{{$processEnv ELASTIC}}/reviews/_doc
Content-Type: application/json

{
    "rating": 5.0,
    "content": "Incredible!",
    "product_id": 123,
    "created_at": "2015-01-28T09:21:51+01:00",
    "author": { 
        "first_name": "Adam",
        "last_name": "Smith",
        "email": "asmith@example.com"
    }
}

###
POST http://{{$processEnv ELASTIC}}/reviews/_doc
Content-Type: application/json

{
    "rating": 4.6,
    "content": "Very useful!",
    "product_id": 123,
    "created_at": "1436011284000",
    "author": { 
        "first_name": "Taylor",
        "last_name": "West",
        "email": "twest@example.com"
    }
}